apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container
        image: sumit0004/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "host.minikube.internal"
        
        # --- NEW: SELF-HEALING PROBES ---
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10 # Wait 10 seconds before checking the first time
          periodSeconds: 15       # Check every 15 seconds after that
          
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5  # Check quickly to see if it's ready for traffic
          periodSeconds: 5